spring:
  cloud:
    config:
      server:
        git:
          search-paths:
  output:
    ansi:
      enabled: always


greet:
  msg: 'hello world'
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true