version: "2"
services:
  cloud-config-server:
    image: "cloud-config-server:1.0"
    ports:
      - "8888:8888"
  cloud-config-client:
    image: "cloud-config-client:1.0"
    volumes:
      - ./wait-for-it.sh:wait-for-it.sh
    ports:
      - "8090:8090"
    command: ["./wait-for-it.sh", "http://cloud-config-server:8888/actuator/health", "--", "python", "app.py"]